branches:
  only:
    - staging
    - master
cache: false
language: node_js
sudo: true
node_js:
- 6
services:
  - postgresql
before_install:
  - rvm install ruby-1.9.3-p551
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
script:
  - scripts/lint-travis.sh
  - npm test
env:
  global:
  - CF_API="https://api.fr.cloud.gov"
  - CF_ORGANIZATION="gsa-18f-federalist"
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  postgresql: "9.5"
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.22.2"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - npm install
  - npm run build
deploy:
  - provider: script
    script: scripts/deploy-travis.sh
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: scripts/deploy-travis.sh
    skip_cleanup: true
    on:
      branch: master
