branches:
  only:
    - staging
    - master
cache:
  yarn: true
language: node_js
sudo: true
node_js:
- 6
services:
  - postgresql
before_install:
  - rvm install ruby-1.9.3-p551
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=$YARN_VERSION
install:
  - yarn --pure-lockfile
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
script:
  - scripts/lint-travis.sh
  - yarn test
env:
  global:
  - CF_API="https://api.fr.cloud.gov"
  - CF_ORGANIZATION="gsa-18f-federalist"
  - CXX=g++-4.8
  - YARN_VERSION=0.24.6-1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  postgresql: "9.5"
before_deploy:
  - export PATH=$HOME:$PATH
  - travis_retry curl -L -o $HOME/cf.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.22.2"
  - tar xzvf $HOME/cf.tgz -C $HOME
  - travis_retry cf install-plugin autopilot -f -r CF-Community
  - yarn build
deploy:
  - provider: script
    script: scripts/deploy-travis.sh
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: scripts/deploy-travis.sh
    skip_cleanup: true
    on:
      branch: master
